/control/verbose 2
/run/verbose 2
/vis/verbose warnings

/run/initialize

/vis/open OGL
/vis/ogl/set/displayListLimit 1000000

/vis/drawVolume
/vis/viewer/set/style surface
#/vis/viewer/set/style wireframe
/vis/scene/add/axes 0 0 0 2 m

# for drawing the tracks
/tracking/storeTrajectory 1
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate

#/vis/filtering/trajectories/create/particleFilter
#/vis/modeling/trajectories/create/drawByParticleID
